Update to work with gdal 3.3.0
natcap/pygeoprocessing pull request #196
Opened 2021-05-24 16:28 UTC by emlys

2021-06-07 18:42 UTC, richpsharp commented
Hi @emlys, I see this is been in draft for a while. Just checking to see if it's ready for review and you just forgot to click the button? np if not.

2021-06-07 19:15 UTC, emlys commented
Thanks @richpsharp yes it is ready! I think I was waiting to see if any of the other invest issues with gdal 3.3.0 were related to pygeoprocessing but they're probably not.

2021-06-08 00:36 UTC, richpsharp requested changes
Two things:
1) can you update `HISTORY.rst` to say that GDAL 3.3.0 is supported? 

2) I'm guessing an automatic python code styling tool was used to format code that was C++ specific. There's changes all throughout the .pyx functions that are doing things like this ('"int *x" to "int * x"; "int&" to "int &"; "<int>" to "<int >", and in template calls things like "Type[x=1] Q" to "Type[x = 1] Q". 

There's so many I stopped commenting on them because if it was automatic maybe you could undo the automatic? 

There are some spacing changes in there which are fine, but I'd prefer it if all the things related to C++ styles were changed back.

2021-06-08 00:36 UTC, richpsharp commented on src/pygeoprocessing/routing/routing.pyx
> +cdef int * D8_YOFFSET = [0, -1, -1, -1, 0, +1, +1, +1]
Was adding this space here intentional? I've always put the * by the variable name when it's a pointer and I think that's fairly standard C++ notation. If not, could you change it back?

2021-06-08 00:36 UTC, richpsharp commented on src/pygeoprocessing/routing/routing.pyx
> +cdef int * D8_REVERSE_DIRECTION = [4, 5, 6, 7, 0, 1, 2, 3]
Ahh I'm guessing it was inconsistent spacing. I'd prefer the * on the variable name rather than the type.

2021-06-08 00:36 UTC, richpsharp commented on src/pygeoprocessing/routing/routing.pyx
> +        priority_queue(Container & )
Why did you add spacing here?

2021-06-08 00:36 UTC, richpsharp commented on src/pygeoprocessing/routing/routing.pyx
> +        void push(T & )
Same question re spacing on this reference?

2021-06-08 00:36 UTC, richpsharp commented on src/pygeoprocessing/routing/routing.pyx
> +        T & top()
another space on a reference?

2021-06-08 00:36 UTC, richpsharp commented on src/pygeoprocessing/routing/routing.pyx
> +        clist[pair[KEY_T, VAL_T]].iterator end()
Spaces on reference

2021-06-08 00:36 UTC, richpsharp commented on src/pygeoprocessing/routing/routing.pyx
> +        void clean(clist[pair[KEY_T, VAL_T]] &, int n_items)
Okay I'm going to stop commenting on this because it's everywhere. I'll put it in the main review comment.

2021-06-08 00:36 UTC, richpsharp commented on src/pygeoprocessing/routing/routing.pyx
> +    cdef LRUCache[int, double*] * lru_cache
for all the spaces that were added I'm surprised there's not one on the `double *` :)

2021-06-08 00:36 UTC, richpsharp commented on src/pygeoprocessing/routing/routing.pyx
> +        self.raster_path = <bytes > raster_path
This is a weird non standard C++ spacing.

2021-06-08 14:32 UTC, emlys commented
Ah I didn't notice it was messing up the cython files formatting. I just undid all of it.

2021-06-09 19:21 UTC, richpsharp reviewed
Hi @emlys, thanks for unrolling those Cython changes, but it looks like the tests are failing for all the Windows builds. I'll hold off approving this PR until you can fix that.

2021-06-10 20:10 UTC, emlys commented
@richpsharp fixed now!

2021-06-15 17:55 UTC, richpsharp approved these changes

2021-06-15 17:55 UTC, merged