pin numpy versions
natcap/pygeoprocessing pull request #237
Opened 2022-01-15 01:35 UTC by emlys

2022-01-15 01:43 UTC, emlys commented on pyproject.toml
> +build-backend = "setuptools.build_meta"
Not quite sure how this is different from the [fallback option](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#fallback-behaviour), but it's included in [an example from the setuptools docs](https://setuptools.pypa.io/en/latest/build_meta.html#how-to-use-it).

2022-01-19 22:30 UTC, phargogh requested changes
`pyproject.toml` looks good to me!  Thanks for pinning these.

Since we have similar conditional numpy version logic in `.github/workflows/build-py-dists.yml`, could you update that workflow file to build wheels with `python -m build --wheel` so that we can remove the duplication of numpy version pinning?

Since this is also kind of a user-facing change (it affects the source and binary distributions), could you also add a note to `HISTORY`?

2022-01-19 23:39 UTC, emlys commented
> could you update that workflow file to build wheels with python -m build --wheel so that we can remove the duplication of numpy version pinning?

Good idea! Did the same thing for building the sdist as well.

> could you also add a note to HISTORY?

Done!

2022-01-19 23:43 UTC, phargogh approved these changes
Great, thank you!  I'm adding my approval here, assuming the tests pass.

2022-01-20 17:04 UTC, merged