Watershed delineation: handling the case where flow_dir doesn't have an SRS.
natcap/pygeoprocessing pull request #338
Opened 2023-08-27 21:43 UTC by phargogh

Also noting this change in HISTORY and testing.

Fixes #254

2023-08-28 18:26 UTC, emlys reviewed
@phargogh this looks good, but I'm not sure I understand when it would be OK to have a missing SRS? How do we know that the flow direction raster intersects with the other inputs?

2023-08-28 18:37 UTC, phargogh commented
> when it would be OK to have a missing SRS? How do we know that the flow direction raster intersects with the other inputs?

Well, we don't know for sure!  But if the units of the geotransform and geometries are all the same, it may be reasonable to assume that the user knows what they are doing and continue running.  So we would be assuming that the inputs are in some projected coordinate system and valid for delineating watersheds.  I don't think that's a reasonable assumption to make in InVEST, specifically, but I think it could be OK for a geoprocessing routine like this.

What do you think?

2023-08-28 19:45 UTC, emlys commented
I wonder if it makes sense to have a larger conversation about this and decide when/if this makes sense in general, so we can be consistent within pygeoprocessing? For instance, maybe it's also ok for the outflow vector to have no SRS? But if both inputs have no SRS, is that a problem?

2023-08-29 05:44 UTC, phargogh commented
The consistency question is a good one, and probably worth a discussion!  I'll add it to the agenda for an upcoming software team call.

In the shorter term, it turns out that we have a valid use case for where there might not be a defined spatial reference: in the various [supported raster formats](https://gdal.org/drivers/raster/index.html) that don't support georeferencing.  Taking this [CEOS](https://gdal.org/drivers/raster/ceos.html#raster-ceos) example [file from the GDAL tests](https://github.com/OSGeo/gdal/blob/master/autotest/gdrivers/data/ceos/IMAGERY-75K.L-3), the SRS's WKT is falsey:

```python
>>> from osgeo import gdal
>>> ds = gdal.Open('/Users/jdouglass/Downloads/IMAGERY-75K.L-3')
>>> ds.GetProjection()
''
```

2023-08-29 20:27 UTC, phargogh commented
Thanks for your thoughts and the review @emlys !  I created a new issue #341 for the general pygeoprocessing question in line with the discussion this morning, and I improved the docstring in the watershed delineation routine.

2023-08-29 20:48 UTC, emlys requested changes
Thanks for adding that note to the docstring! It just looks like some extra carraige returns got in there, otherwise good!

2023-08-29 20:52 UTC, phargogh commented
Huh, I'm so used to my editor chomping them that I missed them in the diff!  Thanks @emlys I think they should be clear now

2023-08-29 21:42 UTC, emlys commented on src/pygeoprocessing/routing/watershed.pyx
> +    Note:
```suggestion
    Note:
```

2023-08-29 21:46 UTC, emlys requested changes
Sorry @phargogh but I'm seeing one more `^M` on line 631, those line ending characters are sneaky!

2023-08-30 18:03 UTC, phargogh commented
Ugh, the lesson for me here is to be _very_ careful when copying code out of a git diff!

Patched and pushed in https://github.com/natcap/pygeoprocessing/pull/338/commits/5ab4a460889e3c1480595028b5bdded033bdc0ba

2023-08-30 18:50 UTC, emlys approved these changes

2023-08-30 18:50 UTC, merged