Check for non-numeric keys in value_map in reclassify raster function #419
natcap/pygeoprocessing pull request #420
Opened 2024-12-16 23:27 UTC by claire-simpson

Check that the `value_map` does not contain any non-numeric keys in the raster reclassify function. This function will fail if there are any None/NA keys in the `value_map` dictionary so instead we're explicitly checking for them upfront to provide the user with a clearer error message. Note that this still allows `numpy.nan` keys to pass. I've also created a test to confirm this check works as anticipated.

Fixes #419

2024-12-17 16:48 UTC, davemfish requested changes
Thanks, @claire-simpson , this is very succinct and effective. Would you please add a note in HISTORY about the new `TypeError` being raised? And I found one little redundant line in the test.

2024-12-17 16:48 UTC, davemfish commented on tests/test_geoprocessing.py
> +        target_nodata = -1
`target_nodata` is defined twice

2024-12-17 17:30 UTC, claire-simpson commented
Thanks @davemfish! I noticed that many of the geoprocessing tests define the ``target_nodata`` two times, may be something to look into?

2024-12-17 18:53 UTC, davemfish commented
> Thanks @davemfish! I noticed that many of the geoprocessing tests define the `target_nodata` two times, may be something to look into?

Interesting, feel free to clean that up for us if you'd like to! It could happen in this PR if you want, or a separate one.

2024-12-18 23:44 UTC, claire-simpson commented
> Interesting, feel free to clean that up for us if you'd like to! It could happen in this PR if you want, or a separate one.

Went ahead and did it. I suspect target_nodata was redefined explicitly as the function called in between the duplicate assignments did set target_nodata but that should be out of scope and therefore unnecessary to reassign target_nodata in the test script

2024-12-19 19:51 UTC, davemfish commented
> Went ahead and did it. I suspect target_nodata was redefined explicitly as the function called in between the duplicate assignments did set target_nodata but that should be out of scope and therefore unnecessary to reassign target_nodata in the test script

Thank you!

2024-12-19 19:52 UTC, davemfish approved these changes

2024-12-19 19:52 UTC, merged