Task/geoprocessing 24 remove python2 things
natcap/pygeoprocessing pull request #77
Opened 2020-05-06 17:31 UTC by richpsharp

Removed all Python 2 patch things, updated docstrings as needed, cleaned up imports, and fixed any open pep8lint issues. No need to update HISTORY since none of these changes are user facing.

closes #24

2020-05-06 17:33 UTC, richpsharp commented
@phargogh, I put you as a reviewer on this since you're the one that made all the Python 2/3 compatible things back in the day and would have a better eye for it. Also I'm merging this into the 2.0 release branch because of all the docstring changes. I *thought* we already changed all the "Parameters" to "Args" but that's not showing up and I'm suspicious so I wanted to make sure it was here. There's no other "non-backwards-compatible" issues though.

2020-05-06 22:12 UTC, phargogh requested changes
Just a couple of comments for you, but it overall looks good to me!

2020-05-06 22:12 UTC, phargogh commented on tests/test_geoprocessing.py
> -
I remember we had talked about removing this, but it still looks like that complicated versioning stuff I had added to `__init__.py` is still in there.  Should it be removed from `__init__.py`?

2020-05-06 22:12 UTC, phargogh commented on tests/test_geoprocessing.py
> -
This is trivial, but doesn't PEP8 call for a blank line here?

2020-05-07 18:44 UTC, richpsharp commented on tests/test_geoprocessing.py
> -
Yes I forgot about those! Patched in 8c02c921416332cfd8b655d89abd3cf9632fcf75

2020-05-07 18:47 UTC, richpsharp commented on tests/test_geoprocessing.py
> -
I looked briefly and couldn't see where PEP8 calls for that, plus my linter didn't say anything, but it didn't say anything when I added a blank line either, so patched in d8f5fcf2df1cfa19d679ed8fb21d295a56ffe234

2020-05-07 18:52 UTC, richpsharp commented
hi @phargogh i made the changes you requested and re-requested your review

2020-05-07 22:55 UTC, phargogh approved these changes
Yep, looks good to me!

2020-05-07 22:57 UTC, merged

2020-05-07 22:58 UTC, phargogh commented
Whoah!  OK @richpsharp @davemfish @dcdenu4 I was just able to resolve a merge conflict myself and not have write access to @richpsharp 's fork.  I'm sure you guys knew about this, but it was quite the surprise to me!